#!/bin/sh

# Source the debconf library
. /usr/share/debconf/confmodule

#Reminder: Don't echo to STDOUT. it messes up debconf

# functions to echo to STDERR or the install log instead of STDOUT
D1_LOG_DIR=/var/log/dataone
logError () {
    echo "$@" 1>&2;
}

log () {
    echo "$@" >> ${D1_LOG_DIR}/dataone-cn-os-core.install.log;
}

log "dataone-cn-os-core/config called."
# Ask the person installing what environment should be installed
#db_fset dataone-cn-os-core/cn.context.label seen false
db_input high dataone-cn-os-core/cn.context.label

# Is this a stand-alone CN, or sync'd via LDAP
db_input high dataone-cn-os-core/cn.openldap.synchronized

# Ask for the LDAP database admin password
db_input high dataone-cn-os-core/cn.openldap.password

# Ask if the CNs should be sync'd
db_input high dataone-cn-os-core/cn.openldap.synchronized
db_go

# If we intend to synchronize, get the unique serverID for LDAP
db_get dataone-cn-os-core/cn.openldap.synchronized
if [ ${RET} = "true" ]; then
    db_input high dataone-cn-os-core/cn.openldap.serverID
fi

db_go
exit 0