#!/bin/bash
# source the debconf library
if [ -e "/usr/share/debconf/confmodule" ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

#if  [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
#    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
#    db_purge
#fi