#!/bin/bash


##################################################################
# Configure the firewall
##################################################################


ufw default deny
ufw allow ssh
ufw allow http
ufw allow https
ufw enable
echo "Completed configuration of ufw firewall."

##################################################################
# Install the dataone private key provided by the user
# This key can not be added to the SVN repository because it is not
# secure to do so -- access to the file must be restricted
##################################################################
KEY_FILE=${HOME}/dataone_org.key
KEY_DIR=/etc/ssl/private/
if [ -e ${KEY_FILE} ]
then
    echo "Copying private key: ${KEY_FILE}."
    cp ${KEY_FILE} ${KEY_DIR}
else
    echo "Key file is missing.  Please provide it as ${KEY_FILE}. Without
    this, SSL will not function properly."
fi
echo "Completed configuration of private keys."

chown -R ${TOMCAT_USER}.${TOMCAT_USER} /etc/tomcat6
chown -R ${TOMCAT_USER}.${TOMCAT_USER} /var/lib/tomcat6
chown -R ${TOMCAT_USER}.${TOMCAT_USER} /var/log/tomcat6
chown -R ${TOMCAT_USER}.${TOMCAT_USER} /var/cache/tomcat6
chown -R ${TOMCAT_USER}.${TOMCAT_USER} /usr/share/tomcat6


echo "Configuration of OS complete."
