#!/bin/sh

PATH=${PATH}:/sbin:/usr/lib/nagios/plugins
export PATH

host=`hostname -f`
hosts='UCSB UNM ORC'
ports='5701 5702 5703'

echo "<<<hazelcast>>>"

for port in ${ports}; do
  for host in ${hosts}; do
    result="`check_tcp -H cn-${host}-1.dataone.org -p ${port}`"
    if [ "X${result}" = "XConnection refused" ]; then
        result="TCP CRIT - ${result}"
    fi
    echo "${host}/${port} : ${result}"
  done
done
